services:
  mariadb:
    build: ./requirements/mariadb
    volumes:
      - db_data:/var/lib/mysql
    secrets:
      - db_password
      - db_root_password
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
    networks:
      - inception_network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-p$(cat /run/secrets/db_root_password)" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  wordpress:
    build: ./requirements/wordpress
    volumes:
      - wp_data:/var/www/html
    secrets:
      - db_password
      - wp_admin_password
      - wp_user_password
    environment:
      MYSQL_HOST: mariadb
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: /run/secrets/db_password
      DOMAIN_NAME: ${DOMAIN_NAME}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_USER: ${WP_USER}
      WP_USER_EMAIL: ${WP_USER_EMAIL}
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - inception_network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pgrep php-fpm7.4 || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    build: ./requirements/nginx
    volumes:
      - wp_data:/var/www/html
    ports:
      - "443:443"
    networks:
      - inception_network
    depends_on:
      wordpress:
        condition: service_healthy
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
    restart: unless-stopped

networks:
  inception_network:
    driver: bridge

volumes:
  db_data:
  wp_data:


secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt
