services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    env_file: ./.env
    restart: unless-stopped
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    secrets:
      - db_password

  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    env_file: ./.env
    restart: unless-stopped
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    expose:
      - "9000"
    secrets:
      - db_password
      - wp_admin_password
      - wp_user_password

  nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    env_file: ./.env
    restart: unless-stopped
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception

secrets:
  db_password:
    file: ./secrets/db_password.txt
  wp_admin_password:
    file: ./secrets/wp_admin_password.txt
  wp_user_password:
    file: ./secrets/wp_user_password.txt

volumes:
  wordpress_data:
    driver_opts:
      o: bind
      device: ${HOME}/data/wordpress
      type: none
  mariadb_data:
    driver_opts:
      o: bind
      device: ${HOME}/data/mariadb
      type: none

networks:
  inception:
    driver: bridge
